version: '3'
services: 
    node:
        build:
            context: .
        tty: true
        environment: 
            - NODE_ENV=production
            - CHOKIDAR_USEPOLLING=true
        volumes: 
            - ./:/usr/src/app
        command: sh -c "cd othello && yarn start"
        ports: 
            - "3000:3000"